import Navbar from '@/components/Navbar'
import Head from 'next/head'


export default function Courses() {
    return (
        <>
            <Head>
                <title>QuizUp</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/logo.svg"/>
            </Head>
            <main className="min-h-screen flex flex-col font-nunito text-white">
            <Navbar />
            </main>
        </>
    )
}