import Head from 'next/head'
import {Inter} from 'next/font/google'
import Hero from '@/components/Hero'
import Navbar from '@/components/Navbar'
import Courses from '@/components/Courses'

const inter = Inter({subsets: ['latin']})

export default function Home() {
    return (
        <>
            <Head>
                <title>QuizUp</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/logo.svg"/>
            </Head>
            <main className="min-h-screen flex flex-col font-nunito text-white">
            <Navbar />
            <Hero />
            <Courses />
            </main>
        </>
    )
}
